zkVerify integration example for on-chain zk proof verification
Galxe/identity-protocol pull request #11
Opened 2024-12-19 20:39 UTC by AndreaRettaroli

## zkVerify
[zkVerify](https://zkverify.io/) is a modular blockchain focused on proof verification. It's specifically enables blockchain networks to offload the computationally heavy and expensive process of zk (zero-knowledge) proof verification, drastically reducing cost. It's support multiple verification schemes, including Groth16.

##Considerations
Assessed that zkVerify can reduce proof verification costs by >90% compared to native verification on Ethereum, at Galxe's scale, this translates to a significant costs dropping - a transformation that could generate millions in savings annually.

Beyond pure cost reduction, this integration opens new possibilities for Web3 identity management. With around 1 million users actively using Galxe Passport, cheaper verification enables more frequent credential checks, enhanced privacy features, and broader accessibility to trustless credential systems for smaller projects.

On a closing thought, we want to remark how specialized verification layers can solve real problems in large-scale identity systems, with the zkVerify-Galxe integration setting a new standard for efficient, accessible credential verification in Web3.

2025-05-08 09:15 UTC, Stumble requested changes
This PR introduces changes that are out of the scope of adding zkVerify as an additional verification stack. For example, the readme file change and additional scripts. It seems to be a direct pull from a fork for the hackathon.

Could you change it accordingly and we will be happy to review

2025-05-12 19:39 UTC, AndreaRettaroli commented
@Stumble updated pr:
- rollback readme
- updated zkverify to latest version
- updated code to match with latest zkverify version

2025-05-13 01:57 UTC, Stumble approved these changes
LGTM

2025-05-13 02:10 UTC, lllluull approved these changes
LGTM

2025-05-13 17:47 UTC, AndreaRettaroliPostNL approved these changes

2025-05-13 17:59 UTC, AndreaRettaroli commented
@Stumble , @lllluull i have no button to merge it, i guess because of some restriction in the settings, hope you can merge on your side directly or try to have a look on branch settings or ruleset. 

<img width="1302" alt="Screenshot 2025-05-13 at 19 42 21" src="https://github.com/user-attachments/assets/6b185fdc-a997-40b7-b630-82bfe980ea9f" />

2025-05-16 10:31 UTC, merged